Build the linear regression model using scikit learn in boston data to predict
'Price' based on other dependent variable.

In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import sklearn
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_boston

boston =load_boston()


In [2]:
bs = pd.DataFrame(boston.data, columns =boston.feature_names)
bs

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [ ]:
boston.feature_names
#column names

In [ ]:
boston.target
#target variable(price of the houses)

In [4]:
#split data into dependent(y) and independent(x) datas.
df_x = bs
df_y = boston.target

In [5]:
#describe the dataset
df_x.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [6]:
#split data into trai and test --> 75% and 25%
x_train,x_test,y_train,y_test= train_test_split(df_x,df_y,test_size=0.25, random_state = 355)
regModel= linear_model.LinearRegression()
regModel.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
#coeffficients for each column of our model
print(regModel.coef_)

In [7]:
# print predictions as model is trained above
y_pred = regModel.predict(x_test)
y_pred

array([11.79886391, 19.00724158, 30.15569938, 23.81625725,  7.00534939,
       24.01290538, 21.02158353, 19.21841711, 43.38294937, 20.62413868,
       26.39616804, 24.04618789, 25.85260347, 17.78208867, 10.52963272,
       33.08009466, 19.30539588, 18.92674579, 24.76923676, 17.35773232,
       19.5632307 , 23.36138113, 32.82075534, 24.93259125, 35.84221429,
       24.64559059, 28.16741177, 34.69448848, 20.65277854, 26.8055867 ,
       21.23512834, 24.86286988, 15.71185577, 20.93978319, 19.14806908,
       24.29673876, 36.95320988, 18.6179615 , 30.29335952, 32.0199193 ,
       22.9310251 , 14.66434179, 19.20891563, 19.50024246, 19.91516961,
       20.22064886, 30.3688808 , 17.65387271, 22.77246687, 18.06842241,
       17.07955317, 19.45278114, 15.35162788, 30.15549026, 46.23137542,
        6.5967418 , 41.02477652, 26.54080841, 16.39023991, 22.4277114 ,
       10.12164792, 23.04344969, 12.70047754, 22.17969611, 24.64430723,
        9.97170547, 27.51050764, 27.18312045, 18.14359002, 22.08

In [8]:
regModel.score(x_train,y_train)

0.730647531347494

In [9]:
regModel.score(x_test,y_test)

0.7519030329262363

In [10]:
#mean squared error value (MSE) to check accuracy. if modelpredicted exact values then mse =0(r2)
# r2= sum(sq(y-y_pred))--> r2 is min then its best fit model
print(np.mean((y_pred-y_test)**2))

22.178426943709656


In [12]:
# split as 67 and 33 %
x_train,x_test,y_train,y_test = train_test_split(df_x,df_y,test_size= 0.33, random_state=42)
regModel.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
y_pred1=regModel.predict(x_test)
y_pred1

array([28.53469469, 36.6187006 , 15.63751079, 25.5014496 , 18.7096734 ,
       23.16471591, 17.31011035, 14.07736367, 23.01064388, 20.54223482,
       24.91632351, 18.41098052, -6.52079687, 21.83372604, 19.14903064,
       26.0587322 , 20.30232625,  5.74943567, 40.33137811, 17.45791446,
       27.47486665, 30.2170757 , 10.80555625, 23.87721728, 17.99492211,
       16.02608791, 23.268288  , 14.36825207, 22.38116971, 19.3092068 ,
       22.17284576, 25.05925441, 25.13780726, 18.46730198, 16.60405712,
       17.46564046, 30.71367733, 20.05106788, 23.9897768 , 24.94322408,
       13.97945355, 31.64706967, 42.48057206, 17.70042814, 26.92507869,
       17.15897719, 13.68918087, 26.14924245, 20.2782306 , 29.99003492,
       21.21260347, 34.03649185, 15.41837553, 25.95781061, 39.13897274,
       22.96118424, 18.80310558, 33.07865362, 24.74384155, 12.83640958,
       22.41963398, 30.64804979, 31.59567111, 16.34088197, 20.9504304 ,
       16.70145875, 20.23215646, 26.1437865 , 31.12160889, 11.89

In [14]:
regModel.score(x_train,y_train)

0.7392344370995025

In [15]:
regModel.score(x_test,y_test)

0.7261570836552479

In [16]:
print(np.mean((y_pred1-y_test)**2))

20.72402343733974


In [17]:
# 70 and 30 
x_train,x_test,y_train,y_test = train_test_split(df_x,df_y,test_size= 0.30, random_state=42)
regModel.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
y_pred2= regModel.predict(x_test)
y_pred2

array([28.64896005, 36.49501384, 15.4111932 , 25.40321303, 18.85527988,
       23.14668944, 17.3921241 , 14.07859899, 23.03692679, 20.59943345,
       24.82286159, 18.53057049, -6.86543527, 21.80172334, 19.22571177,
       26.19191985, 20.27733882,  5.61596432, 40.44887974, 17.57695918,
       27.44319095, 30.1715964 , 10.94055823, 24.02083139, 18.07693812,
       15.934748  , 23.12614028, 14.56052142, 22.33482544, 19.3257627 ,
       22.16564973, 25.19476081, 25.31372473, 18.51345025, 16.6223286 ,
       17.50268505, 30.94992991, 20.19201752, 23.90440431, 24.86975466,
       13.93767876, 31.82504715, 42.56978796, 17.62323805, 27.01963242,
       17.19006621, 13.80594006, 26.10356557, 20.31516118, 30.08649576,
       21.3124053 , 34.15739602, 15.60444981, 26.11247588, 39.31613646,
       22.99282065, 18.95764781, 33.05555669, 24.85114223, 12.91729352,
       22.68101452, 30.80336295, 31.63522027, 16.29833689, 21.07379993,
       16.57699669, 20.36362023, 26.15615896, 31.06833034, 11.98

In [19]:
regModel.score(x_train,y_train)

0.7434997532004697

In [20]:
regModel.score(x_test,y_test)

0.711226005748496

In [21]:
print(np.mean((y_pred2-y_test)**2))

21.517444231176995
