Q1) Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [3]:
import numpy as np

In [33]:
def matrix(vector, n, increasing = False):
    if not increasing:
        output = np.array([x**(n-i-1) for x in vector for i in range(n)]).reshape(vector.size,n)
    elif increasing:
        output =  np.array([x**i for x in vector for i in range(n)]).reshape(vector.size,n)
    return output

vector = np.array([1,2,3,4])
opt_col = 3
opt_mat1 = matrix(vector, opt_col)            
opt_mat2 = matrix(vector, opt_col,True)
opt_mat3= matrix(vector, opt_col,False)

print("when increaing is not given, default set to FALSE: \n",opt_mat1)
print("when increaing is TRUE given: \n",opt_mat2)
print("when increaing is FALSE given: \n",opt_mat3)



when increaing is not given, default set to FALSE: 
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
when increaing is TRUE given: 
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]
when increaing is FALSE given: 
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]


Q2) Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [34]:
def moving_avg(in_array, w,num):
    avgs =[]
    print("input: ",in_array)
    n=1
    while(n<=num):
        sum =0
        for i in range(0,w):
            sum+= in_array[i]
        avg = sum/w
        avgs.append(round(avg,2))
        in_array=np.delete(in_array,[0])
        n+=1
    return avgs

in_array =np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
#in_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
window = 3
num= in_array.size-window+1
output = moving_avg(in_array,window,num)
print("The moving average sequence has ",num," values. Rounded to 2 decimal places")
print("Moving average sequence: ",output)

input:  [  3   5   7   2   8  10  11  65  72  81  99 100 150]
The moving average sequence has  11  values. Rounded to 2 decimal places
Moving average sequence:  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
